# Application Name
spring.application.name=order-ui-service

# Server Port
server.port=8080

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.root=INFO
logging.level.fit.iuh=DEBUG
logging.level.org.springframework.web=INFO

